bot_save_freq: 100
bot_type: LSTMPPOBot
buffer_size: 4000
clip_ratio: 0.3
epoch: 10
game_data_flush_freq: 100
lr: 0.0001
mini_batch_size: 1028
num_of_worker: 10
opponent_buf_limit: 10
opponent_update_freq: 10
